package Hotel.DBEntity;
// Generated 27.05.2017 21:47:42 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Roomstatus generated by hbm2java
 */
public class Roomstatus implements java.io.Serializable {

    private int id;

    private String status;

    private Set<Roomhistory> roomhistories = new HashSet<Roomhistory>(0);

    public Roomstatus() {
    }

    public Roomstatus(int id, String status) {
        this.id = id;
        this.status = status;
    }

    public Roomstatus(int id) {
        this.id = id;
    }

    public Roomstatus(int id, String status, Set<Roomhistory> roomhistories) {
        this.id = id;
        this.status = status;
        this.roomhistories = roomhistories;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Set<Roomhistory> getRoomhistories() {
        return this.roomhistories;
    }

    public void setRoomhistories(Set<Roomhistory> roomhistories) {
        this.roomhistories = roomhistories;
    }

}
