package Hotel.DBEntity;
// Generated 27.05.2017 20:31:12 by Hibernate Tools 4.3.1

/**
 * Roomuser generated by hbm2java
 */
public class Roomuser implements java.io.Serializable {

    private Integer id;

    private String UName;

    private String ULogin;

    private String UPass;

    private String UMail;

    private String UPhone;

    private String status;

    public Roomuser() {
    }

    public Integer getId() {
        return this.id;
    }

    public Roomuser setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getUName() {
        return this.UName;
    }

    public Roomuser setUName(String UName) {
        this.UName = UName;
        return this;
    }

    public String getULogin() {
        return this.ULogin;
    }

    public Roomuser setULogin(String ULogin) {
        this.ULogin = ULogin;
        return this;
    }

    public String getUPass() {
        return this.UPass;
    }

    public Roomuser setUPass(String UPass) {
        this.UPass = UPass;
        return this;
    }

    public String getUMail() {
        return this.UMail;
    }

    public Roomuser setUMail(String UMail) {
        this.UMail = UMail;
        return this;
    }

    public String getUPhone() {
        return this.UPhone;
    }

    public Roomuser setUPhone(String UPhone) {
        this.UPhone = UPhone;
        return this;
    }

    public String getStatus() {
        return this.status;
    }

    public Roomuser setStatus(String status) {
        this.status = status;
        return this;
    }

}
